version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio_MLpipeline
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data

  mlflow-server:
    build: .
    container_name: mlflow_server_MLpipeline
    ports:
      - "5000:5000"
    volumes:
    - ./mlflow:/app/mlflow
    - ./mlflow.db:/app/mlflow.db
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root s3://mlflow-artifacts/
      --host 0.0.0.0
    working_dir: /app/mlflow

volumes:
  minio-data:
